### ISSUE TITLE
Some Server Notice settings have no effect

### ISSUE THREAD

**Issue by matrixbot** [element-hq/dendrite#2815]
*This issue was originally created by [**@tux93**](https://github.com/tux93) at <https://github.com/matrix-org/dendrite/issues/2815>.*

### Background information
- **Dendrite version or git SHA**: 0.10.3+git.0.81dbad39
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: postgres-14-150400
- **Running in Docker?**: no
- **`go version`**: go1.19-1.19.1
- **Client used (if applicable)**: Element 1.11.8 / FluffyChat 1.6.4

### Description

- **What** is the problem: The Server Notice settings `display_name` and `avatar_url` have no effect
- **Who** is affected: Any local user receiving a Server Notice
- **How** is this bug manifesting: Instead of the configured Display Name a Server Notice message is shown with the local_part Sender Name, the Sender has no Avatar
- **When** did this first appear: Has been the case for as long as I am using Dendrite (~ 0.9.4)

### Steps to reproduce

- Set up dendrite with enabled server notices
- Send a notice to a local user 
- The user is invited to a room, the room has the configured name but the sender Display Name and Avatar are not set as configured

My Server Notice configuration:
```
  server_notices:
    enabled: true
    local_part: "_notice"
    display_name: "Server Notices"
    avatar_url: "<mxc url aquired by using 'View Source' on an image sent in a unencrypted room>"
    room_name: "Server Notices"
```

This is how the Notices are shown in the Client:
![Screenshot_20221020-144648_FluffyChat](https://user-images.githubusercontent.com/1749593/196955025-c124830d-d141-4cea-a3e3-3824c9317bdd.jpg)
