### ISSUE TITLE
SQLite is not working

### ISSUE THREAD

**Issue by matrixbot** [element-hq/dendrite#3435]
*This issue was originally created by [**@paigeadelethompson**](https://github.com/paigeadelethompson) at <https://github.com/matrix-org/dendrite/issues/3435>.*

followed the documentation @ https://matrix-org.github.io/dendrite/installation/manual/database and it don't work

```
monolith-1  | time="2024-09-28T13:21:13.627063518Z" level=panic msg="failed to connect to room server db" error="near \"SEQUENCE\": syntax error"
monolith-1  | panic: (*logrus.Entry) 0xc0002682a0
```

```
  database:
    connection_string: file:dendrite_component.db
    max_open_conns: 5
    max_idle_conns: 5
    conn_max_lifetime: -1
```

tried `file:///` and it dont work

**Comment by vxtls** [comment]
room_server:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/room_server.db"

federation_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/federation_api.db"

key_server:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/key_server.db"

media_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/media_api.db"

sync_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/sync_api.db"

user_api:
  account_database:
    type: sqlite3
    connection_string: "file:/data/chat/user_api.db"

relay_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/relay_api.db"

mscs:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/mscs.db"

**Comment by vxtls** [comment]
`room_server:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/room_server.db"

federation_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/federation_api.db"

key_server:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/key_server.db"

media_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/media_api.db"

sync_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/sync_api.db"

user_api:
  account_database:
    type: sqlite3
    connection_string: "file:/data/chat/user_api.db"

relay_api:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/relay_api.db"

mscs:
  database:
    type: sqlite3
    connection_string: "file:/data/chat/mscs.db"
`

**Comment by tecspda** [comment]
## Work version for sqlite3:
**docker-compose.yml**:
```
version: '3'

services:
  dendrite:
    image: matrixdotorg/dendrite-monolith:latest
    container_name: dendrite
    restart: unless-stopped
    volumes:
      - ./dendrite-data:/var/dendrite
      - ./dendrite-data/dendrite.yaml:/var/dendrite/dendrite.yaml

    ports:
      - "127.0.0.1:8008:8008"  # HTTP Port for local access
      - "127.0.0.1:8448:8448"  # Port of the Federation, also through a local interface
    networks:
      - matrix_network
    environment:
      - DENDRITE_JETSTREAM_IN_MEMORY=true
    command: [
      "--config", "/var/dendrite/dendrite.yaml",
      "--really-enable-open-registration"  # Добавляем флаг в команду
    ]

volumes:
  dendrite-data:
    driver: local

networks:
    matrix_network:
      driver: bridge
```

**./dendrite-data/dendrite.yaml**:
```
server_name: "matrix.yourserver.com"

database:
  connection_string: file:/var/dendrite/dendrite.db

listen:
  http: ":8008"
  https: ":8448"

tls:
  disable_tls: true   # Disconnect TLS at the Dendrite level, as TLS processes reverse proxy

client_api:
  registration_disabled: false  # Disconnect registration (this is for my project)
  registration_shared_secret: ""  # If you need registration through a general secret
  enable_registration_captcha: false

media_api:
  base_path: "/var/dendrite/media"
  max_file_size_bytes: 10485760  # 10MB
  dynamic_thumbnails: false
  database:
    connection_string: file:/var/dendrite/mediaapi.db

federation:
  enable: true
  server_name: matrix.draganmobile.online

federation_api:
  disable_tls_validation: false
  database:
    connection_string: file:/var/dendrite/federationapi.db

# Настройки JetStream (for processing events)
jetstream:
  storage_path: "/var/dendrite/jetstream"
  in_memory: true

key_server:
  database:
    connection_string: file:/var/dendrite/keyserver.db

# Synchronization settings for customers
sync_api:
  database:
    connection_string: file:/var/dendrite/syncapi.db

room_server:
  database:
    connection_string: file:/var/dendrite/roomserver.db

user_api:
  account_database:
    connection_string: file:/var/dendrite/accounts.db
  device_database:
    connection_string: file:/var/dendrite/devices.db

public_rooms_api:
  database:
    connection_string: file:/var/dendrite/publicroomsapi.db

# Settings of server keys
mscs:
  database:
    connection_string: file:/var/dendrite/mscs.db

push_server:
  database:
    connection_string: file:/var/dendrite/pushserver.db

relay_api:
  database:
    connection_string: file:/var/dendrite/relayapi.db

global:
  server_name: "matrix.draganmobile.online"
  private_key: "/var/dendrite/matrix_key.pem"
  key_id: "ed25519:auto"
```
