### ISSUE TITLE
Hwo to configuration for opentracing

### ISSUE THREAD

**Issue by Capricornwqh** [element-hq/dendrite#3483]
```
tracing:
  enabled: false
  jaeger:
    serviceName: ""
    disabled: false
    rpc_metrics: false
    tags: []
    sampler: null
    reporter: null
    headers: null
    baggage_restrictions: null
    throttler: null
```

https://github.com/matrix-org/dendrite/tree/master/docs/tracing
page not found
